version: "2"

linters:
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck # Now includes gosimple and stylecheck
    - unconvert
    - unused
    - whitespace
    - govet # Ensure this is included

  settings:
    errcheck:
      # Add any errcheck settings here
      exclude-functions:
        - io.Copy(*bytes.Buffer)

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style

    gosec:
      # Add gosec settings
      excludes:
        - G104 # Errors unhandled

    staticcheck:
      # Configure staticcheck (includes gosimple/stylecheck checks)
      checks: ["all"]

    revive:
      # Add revive rules
      rules:
        - name: exported
          disabled: false

  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives

    rules:
      - path: '_test\.go'
        linters:
          - errcheck
          - gosec

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true

    goimports:
      local-prefixes:
        - github.com/mattermost/mattermost-plugin-demo

output:
  formats:
    text:
      path: stdout
      colors: true
      print-linter-name: true

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false
