version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.12-node

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: make check-style

  test:
    executor:
      name: default
    steps:
      - checkout
      - run: make test

workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - test
