name: ci
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

permissions:
  contents: read

env:
  IS_CI: true

jobs:
  plugin-ci:
    uses: mattermost/actions-workflows/.github/workflows/plugin-ci.yml@mage
    secrets: inherit
    with:
      mage-version: v1.15.0
